# @package _global_

dataset_uri: mlflow-artifacts:/111/8754a5c495d14ad2b5eacfcafd8087f5/artifacts/dataset.csv
annot_path: /mnt/data/IKEM/colon/IBD_AI/dysplasia/annotations
level: 3
max_concurrent: 4
target_groups:
  "LG Dysplasia": 255
  "HG Dysplasia": 128
  "Loose HG Dysplasia": 128

metadata:
  run_name: "✍ Annotation masks Creation"
  description: "Create Annotation masks from manual annotations"