# @package _global_

dataset_uri: mlflow-artifacts:/111/6cb6ff6f15844187b2f8f8218f35bec0/artifacts/dataset.csv
request_timeout: 300
max_concurrent: 5

qc_parameters:
  mask_level: 3
  sample_level: 1
  check_residual: True
  check_folding: False
  check_focus: True
  wb_correction: True


metadata:
  run_name: "🎭 QC Masks Creation"
  description: Quality control masks for dysplasia project