# @package _global_

defaults:
  - /default
  - _self_

level: ???
max_concurrent: ???
mlflow_artifact_path: tissue_masks

metadata:
  run_name: Tissue Masks
  description: ???
  hyperparams:
    level: ${level}
