# @package _global_

dataset_uri: mlflow-artifacts:/111/6cb6ff6f15844187b2f8f8218f35bec0/artifacts/dataset.csv
level: 3
max_concurrent: 4

metadata:
  run_name: "🧻 Tissue masks Creation"
  description: "Create tissue masks for dysplasia project"