# @package _global_

defaults:
  - /dataset/processed_w_tiling@_here_
  - _self_

mlflow_uris:
  filtered: 
    train: mlflow-artifacts:/111/bc3c85b1f4774d8d97bb15dd20f95838/artifacts/filtered_tiles/train
    test_preliminary: mlflow-artifacts:/111/bc3c85b1f4774d8d97bb15dd20f95838/artifacts/filtered_tiles/test_preliminary
    test_final: mlflow-artifacts:/111/bc3c85b1f4774d8d97bb15dd20f95838/artifacts/filtered_tiles/test_final